apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-default
  labels:
    app: ubuntu
spec:
  containers:
    - image: ghcr.io/pluhin/busy-box:latest
      command:
        - "sleep"
        - "120"
      imagePullPolicy: IfNotPresent
      name: ubuntu-default
