name: Test minikube installation

#on:
#  release:
#    types: [published]

on:
  push:
    branches: [ "main" ]

jobs:
  setup_minikube:
    name: test minikube setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Minikube
        uses: medyagh/setup-minikube@latest
        id: minikube

      - name: Build image
        run: |
          minikube status
          minikube image build -t andybar69/githubaction:v1 .

      - name: kubectl
        run: kubectl get pods -A
